export type pmgOptions = {
    activeIndex?: number,
    positionPreviews?: string,
    visiblePreviews?: boolean,
    countPreSlides?: number,
    spaceBetween?: number,
    previewWidth?: number,
    previewHeight?: number,
    speedAnimScroll?: number,
    breakpoints?: object,
    objectFitPicture?: string,
    animSlide?: string | boolean,
    borderRadius?: number | boolean,
    fullScreen?: object | boolean,
    autoPlay?: number | boolean,
    pagination?: boolean,
    swipeSlider?: boolean,
    onCenterPreviews?: boolean,
    loop?: boolean,
}