export type initOptions = {
    positionPreviews?: string,
    visiblePreviews?: boolean,
    countPreSlides?: number,
    spaceBetween?: number,
    slideWidth?: number,
    slideHeight?: number,
    speedAnim?: number,
    breakpoints?: object,
    borderRadius?: number | boolean,
    fullScreen?: object | boolean,
    autoPlay?: number | boolean,
    pagination?: boolean,
    swipeSlider?: boolean,
    loop?: boolean,
}