export type pmgTemplate = {
    wrapper?: HTMLElement,
    wrapperWidth?: number,
    wrapperHeight?: number,
    innerPreviewsWidth?: number,
    innerPreviewsHeight?: number,
    innerPreviews?: HTMLElement,
    track?: HTMLElement,
    innerPicture?: HTMLElement,
    mainPicture?: HTMLElement,
    controls?: HTMLElement,
    btnScreen?: HTMLElement,
    arrowsSlider?: HTMLElement,
    previews?: NodeListOf<Element>,
}