export type pmgTemplate = {
    gallery?: HTMLElement,
    wrapper?: HTMLElement,
    wrapperWidth?: number,
    wrapperHeight?: number,
    innerPreviewsWidth?: number,
    innerPreviewsHeight?: number,
    innerPreviews?: HTMLElement,
    track?: HTMLElement,
    innerPicture?: HTMLElement,
    mainPicture?: HTMLElement,
    controls?: HTMLElement,
    btnScreen?: HTMLElement,
    pagination?: HTMLElement,
    paginationItems?: NodeListOf<Element>,
    arrowsSlider?: Element[],
    previews?: NodeListOf<Element>,
}